config/routes.rb
Timelord::Application.routes.draw do

  get 'account/login', :controller => 'account', :action => 'login'
  get 'account/logout', :controller => 'account', :action => 'logout'
  get 'account/:id/edit', :controller => 'account', :action => 'edit'
  put 'account/1', :controller => 'account', :action => 'update'

  resources :users

  resources :work_entries

  resources :codes

  resources :locations

  get '/', :controller => 'work_entries', :action => 'new'
  get 'nav', :controller => 'nav', :action => 'index'
  get 'nav/:action', :controller => 'nav'

  get 'locations/:id/codes(.:format)', :controller => 'locations', :action => 'codes'

  get 'invoice', :controller => 'invoice', :action => 'index'
  get 'invoice/preview(.:format)', :controller => 'invoice', :action => 'preview'
end

app/models/code.rb
class Code < ActiveRecord::Base
  belongs_to :location
  has_many :work_entries, -> { order('worked_at, created_at') }

  scope :display_order, lambda { includes(:location).order('locations.name', 'codes.name') }

  def full_name
    "#{code} - #{name}"
  end
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController

  before_filter :admin_logged_in

  # GET /codes
  # GET /codes.json
  def index
    @codes = Code.display_order.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @codes }
    end
  end

  # GET /codes/1
  # GET /codes/1.json
  def show
    @code = Code.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @code }
    end
  end

  # GET /codes/new
  # GET /codes/new.json
  def new
    @code = Code.new
    @locations = Location.order(:name)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @code }
    end
  end

  # GET /codes/1/edit
  def edit
    @code = Code.find(params[:id])
    @locations = Location.order(:name)
  end

  # POST /codes
  # POST /codes.json
  def create
    @code = Code.new(params.permit(:code))

    respond_to do |format|
      if @code.save
        format.html { redirect_to @code, notice: 'Code was successfully created.' }
        format.json { render json: @code, status: :created, location: @code }
      else
        format.html { render action: "new" }
        format.json { render json: @code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /codes/1
  # PUT /codes/1.json
  def update
    @code = Code.find(params[:id])

    respond_to do |format|
      if @code.update_attributes(params.permit(:code))
        format.html { redirect_to @code, notice: 'Code was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /codes/1
  # DELETE /codes/1.json
  def destroy
    @code = Code.find(params[:id])
    @code.destroy

    respond_to do |format|
      format.html { redirect_to codes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/views/codes/_form.html.erb
<%= form_for(@code) do |f| %>
  <% if @code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@code.errors.count, "error") %> prohibited this code from being saved:</h2>

      <ul>
      <% @code.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location_id %><br />
    <%= select_tag "code_location_id", options_from_collection_for_select(@locations, :id, :name, @code.location_id), {:name => 'code[location_id]'} %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/codes/edit.html.erb
<h1>Editing Code</h1>

<%= render 'form' %>

<%= link_to 'Show', @code %> |
<%= link_to 'All Codes', codes_path %>

app/views/codes/index.html.erb
<h1>Codes</h1>

<%= paginate @codes %><br/>

<table>
  <tr>
    <th>Location</th>
    <th>Code</th>
    <th>Name</th>
    <th></th>
  </tr>

<% @codes.each do |code| %>
  <tr>
    <td><%= code.location.name %></td>
    <td><%= code.code %></td>
    <td><%= code.name %></td>
    <td class="actions">
      <%= link_to image_tag('information.png'), code %>
      <%= link_to image_tag('edit.png'), edit_code_path(code) %>
      <%= link_to image_tag('delete.png'), code, confirm: 'Are you sure?', method: :delete %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to image_tag('add.png'), new_code_path %> <%= link_to 'New Code', new_code_path %>

app/views/codes/new.html.erb
<h1>New Code</h1>

<%= render 'form' %>

<%= link_to 'All Codes', codes_path %>

app/views/codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Location:</b>
  <%= @code.location.name %>
</p>

<p>
  <b>Code:</b>
  <%= @code.code %>
</p>

<p>
  <b>Name:</b>
  <%= @code.name %>
</p>


<%= link_to 'Edit', edit_code_path(@code) %> |
<%= link_to 'All Codes', codes_path %>