config/routes.rb
Timelord::Application.routes.draw do

  get 'account/login', :controller => 'account', :action => 'login'
  get 'account/logout', :controller => 'account', :action => 'logout'
  get 'account/:id/edit', :controller => 'account', :action => 'edit'
  put 'account/1', :controller => 'account', :action => 'update'

  resources :users

  resources :work_entries

  resources :codes

  resources :locations

  get '/', :controller => 'work_entries', :action => 'new'
  get 'nav', :controller => 'nav', :action => 'index'
  get 'nav/:action', :controller => 'nav'

  get 'locations/:id/codes(.:format)', :controller => 'locations', :action => 'codes'

  get 'invoice', :controller => 'invoice', :action => 'index'
  get 'invoice/preview(.:format)', :controller => 'invoice', :action => 'preview'
end

app/models/work_entry.rb
class WorkEntry < ActiveRecord::Base

  belongs_to :code
  belongs_to :user

  scope :in_month, lambda { |user_id, year, month|
    if user_id
      where('user_id = ? and extract (year from worked_at) = ? and extract(month from worked_at) = ?', user_id, year, month)
    else                        # used by admins only
      where('extract (year from worked_at) = ? and extract(month from worked_at) = ?', year, month)
    end
  }

  # Return min year, min year month, max year, max year month. If user is
  # nil, return min/max dates for all work entries.
  def self.min_max_dates_for_user(user)
    sql = "select min(worked_at), max(worked_at) from #{table_name}"
    if user
      sql << " where user_id = #{user.id}"
    end

    logger.debug "ABOUT TO SELECT"
    min_str, max_str = *connection.query(sql).first
    min_str =~ /(\d{4})-(\d{2})-\d{2}/
    min_year, min_year_month = $1, $2
    max_str =~ /(\d{4})-(\d{2})-\d{2}/
    max_year, max_year_month = $1, $2
    logger.debug [min_year.to_i, min_year_month.to_i, max_year.to_i, max_year_month.to_i].inspect # DEBUG
    logger.debug "ABOUT TO RETURN"
    [min_year.to_i, min_year_month.to_i, max_year.to_i, max_year_month.to_i]
  end

  # Converts minutes to a string like "d:hh:mm".
  def self.minutes_as_duration(minutes)
    return nil unless minutes
    mins = minutes % 60
    hours = minutes / 60
    "#{hours}:#{'%02d' % mins}"
  end

  # Converts a string like "d:hh:mm" to minutes.
  def self.duration_as_minutes(dur)
    m, h = dur.split(/:/).reverse
    m.to_i + h.to_i * 60
  end

  # Returns minutes as a string like "d:hh:mm".
  def minutes_as_duration
    WorkEntry.minutes_as_duration(self.minutes)
  end
end

app/controllers/work_entries_controller.rb
class WorkEntriesController < ApplicationController

  before_filter :logged_in

  # GET /work_entries
  # GET /work_entries.json
  def index
    @order = params[:order] || session[:order] || 'desc'
    @order = 'desc' unless %w(asc desc).include?(@order.downcase) # default value; also avoids SQL hacks
    session[:order] = @order

    @year_month = (params[:year_month] || session[:year_month] || '').to_i
    session[:year_month] = @year_month

    admin_create_work_user_select_ivars

    query = WorkEntry.order("worked_at #{@order}")
    user_id = if @curr_user.admin?
                @work_user ? @work_user.id : nil
              else
                @curr_user.id
              end
    if @year_month != 0
      year, month = *year_month_int_to_year_and_month(@year_month)
      query = query.in_month(user_id, year, month)
    else
      query = query.where('user_id = ?', user_id) if user_id
    end

    @months = work_months_options(@work_user, true)

    @page = params[:page]
    @work_entries = query.page(@page)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @work_entries }
    end
  end

  # GET /work_entries/1
  # GET /work_entries/1.json
  def show
    @work_entry = WorkEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @work_entry }
    end
  end

  # GET /work_entries/new
  # GET /work_entries/new.json
  def new
    @work_entry = WorkEntry.new
    @locations = Location.order(:name)
    @initial_codes = Code.where(location_id: @locations.first.id).all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @work_entry }
    end
  end

  # GET /work_entries/1/edit
  def edit
    @work_entry = WorkEntry.find(params[:id])
    @locations = Location.order(:name)
    @initial_codes = Code.where(location_id: @work_entry.code.location.id).all
  end

  # POST /work_entries
  # POST /work_entries.json
  def create
    @work_entry = WorkEntry.new(duration_to_minutes(params[:work_entry]))

    respond_to do |format|
      if @work_entry.save
        format.html { redirect_to @work_entry, notice: 'Work entry was successfully created.' }
        format.json { render json: @work_entry, status: :created, location: @work_entry }
      else
        format.html { render action: "new" }
        format.json { render json: @work_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /work_entries/1
  # PUT /work_entries/1.json
  def update
    @work_entry = WorkEntry.find(params[:id])

    respond_to do |format|
      if @work_entry.update_attributes(duration_to_minutes(params[:work_entry]))
        format.html { redirect_to @work_entry, notice: 'Work entry was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @work_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_entries/1
  # DELETE /work_entries/1.json
  def destroy
    @work_entry = WorkEntry.find(params[:id])
    @work_entry.destroy

    respond_to do |format|
      format.html { redirect_to work_entries_url }
      format.json { head :ok }
    end
  end

  # Creates new hash with :minutes created by parsing that value as a string
  # from the incoming hash.
  def duration_to_minutes(param_hash)
    param_hash = param_hash.symbolize_keys
    param_hash[:minutes] = WorkEntry.duration_as_minutes(param_hash[:minutes])
    param_hash
  end

end

app/helpers/work_entries_helper.rb
module WorkEntriesHelper
end

app/views/work_entries/_form.html.erb
<%= form_for(@work_entry) do |f| %>
  <% if @work_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work_entry.errors.count, "error") %> prohibited this work_entry from being saved:</h2>

      <ul>
      <% @work_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id %>
  <div class="field">
    <%= label_tag :location, 'Location' %><br />
    <%= select_tag "locations", 
        options_from_collection_for_select(@locations, :id, :name, @work_entry.code_id ? @work_entry.code.location.id : nil) %>
  </div>
  <div class="field">
    <%= f.label :code_id %><br />
    <%= collection_select(:work_entry, :code_id, @initial_codes, :id, :full_name) %>
  </div>
  <div class="field">
    Date<br />
    <%= f.date_select :worked_at %>
  </div>
  <div class="field">
    <%= f.label :minutes, 'Time Spent' %><br />
    <%= f.text_field :minutes, value: @work_entry.minutes_as_duration %>
    <span class="note">examples: 1:15, 2:45, 0:15, 15, 90</span>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/work_entries/edit.html.erb
<h1>Editing Work Entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @work_entry %> |
<%= link_to 'All Work Entries', work_entries_path %>

app/views/work_entries/index.html.erb
<h1>Work Entries</h1>

<table class="list-nav">
  <tr>
    <td><%= paginate @work_entries, :params => {:order => @order} %></td>
    <td class="right">
      <% if @curr_user.admin? %>
        <form action="">
          Show user: <%= select_tag "work_user", options_for_select(@work_user_options, :selected => @work_user ? @work_user.id : nil), :onchange => 'submit()' %>
        </form>
      <% end %>
      <form action="">
        Show month: <%= select_tag "year_month", options_for_select(@months, :selected => @year_month), :onchange => 'submit()' %>
      </form>
    </td>
  </tr>
</table>

<br/>

<table>
  <tr>
    <th>Code</th>
    <th>
      Worked<br/>At 
      <% if @order == 'asc' %>
        <%= link_to image_tag('up.png'), "?page=#{@page}&order=desc"
            %><%= image_tag 'down_disabled.png' %>
      <% else %>
        <%= image_tag 'up_disabled.png'
            %><%= link_to image_tag('down.png'), "?page=#{@page}&order=asc" %>
      <% end %>
    </th>
    <th>Time Spent</th>
    <th>Rate</th>
    <th>Fee</th>
    <th>Note</th>
    <th></th>
  </tr>

<% @work_entries.each do |work_entry| %>
  <tr>
    <td><%= work_entry.code.full_name %></td>
    <td><%= work_entry.worked_at %></td>
    <td class="right"><%= work_entry.minutes_as_duration %></td>
    <td class="right"><%= money_str(work_entry.rate_cents) %></td>
    <td class="right"><%= money_str(work_entry.fee_cents) %></td>
    <td><%= work_entry.note %></td>
    <td class="actions">
      <%= link_to image_tag('information.png'), work_entry %>
      <%= link_to image_tag('edit.png'), edit_work_entry_path(work_entry) %>
      <%= link_to image_tag('delete.png'), work_entry, confirm: 'Are you sure?', method: :delete %> </td>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to image_tag('add.png'), new_work_entry_path %> <%= link_to 'New Work Entry', new_work_entry_path %>

app/views/work_entries/new.html.erb
<h1>New Work Entry</h1>

<%= render 'form' %>

<%= link_to 'All Work Entries', work_entries_path %>

app/views/work_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @work_entry.code.full_name %>
</p>

<p>
  <b>Worked at:</b>
  <%= @work_entry.worked_at %>
</p>

<p>
  <b>Time Spent:</b>
  <%= @work_entry.minutes_as_duration %>
</p>

<p>
  <b>Rate (Cents):</b>
  <%= @work_entry.rate_cents %>
</p>

<p>
  <b>Fee (Cents):</b>
  <%= @work_entry.fee_cents %>
</p>

<p>
  <b>Note:</b>
  <%= @work_entry.note %>
</p>


<%= link_to 'Edit', edit_work_entry_path(@work_entry) %> |
<%= link_to 'All Work Entries', work_entries_path %>